name: insult_me
description: Unleash your inner dynamo!
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.10
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.2
  flutter_datetime_picker: ^1.5.1
  intl: ^0.19.0
  flutter_onboarding_slider: ^1.0.11
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  sqflite: ^2.3.2
  path: ^1.8.3
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/onboarding/welcome.svg
    - assets/images/onboarding/boost.svg
    - assets/images/onboarding/time.svg
    - assets/images/onboarding/share.svg
    - assets/images/onboarding/simple.svg
    - assets/data/insults.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/icon.png
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: '#ffffff'

flutter_native_splash:
  color: '#ffffff'
  image: assets/images/logo.png
  color_dark: '#3d3935'
  image_dark: assets/images/logo-dark.png
  android_12:
    image: assets/images/logo.png
    color: '#ffffff'
    icon_background_color: '#3d3935'
    image_dark: assets/images/logo-dark.png
    color_dark: '#3d3935'
    icon_background_color_dark: '#ffffff'
